import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Route as RouteType } from "@/utils/globalTypes";
import NavItem from "./components/navigation/NavItem";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const routes: RouteType[] = [
  { title: "Dashboard", href: "/dashboard", seg: "dashboard" },
  { title: "Home", href: "/", seg: null },
  { title: "Play", href: "/play", seg: "play" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-screen h-[90vh]">{children}</main>
        <nav className="w-[90vw] h-[10vh] mx-auto flex justify-around items-center">
          {routes.map((route: RouteType) => {
            return (
              <NavItem href={route.href} key={route.href} seg={route.seg}>
                {route.title}
              </NavItem>
            );
          })}
        </nav>
      </body>
    </html>
  );
}
